DROP TABLE IF EXISTS USERTYPE;
DROP TABLE IF EXISTS GLUCOSEMEASUREMENT;
CREATE TABLE USERTYPE (ID INT PRIMARY KEY, NAME VARCHAR(64), DESCRIPTION VARCHAR(64));
CREATE TABLE GLUCOSEMEASUREMENT(
  ID INT PRIMARY KEY,
  GLUCOSEVALUE INT,
  MEASUREDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
insert into USERTYPE (id, name, description) values (1, 'User', 'a normal user');
insert into USERTYPE (id, name, description) values (2, 'Admin', 'an admin user');
INSERT INTO GLUCOSEMEASUREMENT (ID, GLUCOSEVALUE) VALUES (1, 6);
INSERT INTO GLUCOSEMEASUREMENT (ID, GLUCOSEVALUE) VALUES (2, 7);
INSERT INTO GLUCOSEMEASUREMENT (ID, GLUCOSEVALUE) VALUES (3, 8);
INSERT INTO GLUCOSEMEASUREMENT (ID, GLUCOSEVALUE) VALUES (4, 12);
INSERT INTO GLUCOSEMEASUREMENT (ID, GLUCOSEVALUE) VALUES (5, 13);
